# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - develop

# List of jobs
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - name: Chromatic Deployment
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack on Success
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          if_mention: failure,cancelled
          mention: here
          author_name: ${{ github.actor }}
          text: |
            Chromatic build finished!
            - Chromatic : ${{ steps.chromatic.outputs.buildUrl }}
            - Storybook : ${{ steps.chromatic.outputs.storybookUrl }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
